# Generated by Django 4.2.19 on 2025-04-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='image',
            field=models.ImageField(blank=True, default='league_images/default_league.png', upload_to='league_images/'),
        ),
    ]
