# Generated by Django 4.2.19 on 2025-03-31 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('sports', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_leagues', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=255)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('event_name', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=100)),
                ('market_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_events', to='groups.league')),
            ],
        ),
        migrations.CreateModel(
            name='LeagueInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='groups.league')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('league', 'to_user')},
            },
        ),
        migrations.RemoveField(
            model_name='groupevent',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupinvite',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupinvite',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='group',
        ),
        migrations.DeleteModel(
            name='BettingGroup',
        ),
        migrations.DeleteModel(
            name='GroupEvent',
        ),
        migrations.DeleteModel(
            name='GroupInvite',
        ),
        migrations.AddField(
            model_name='bet',
            name='league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='groups.league'),
            preserve_default=False,
        ),
    ]
