# Generated by Django 4.2.19 on 2025-03-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_rename_models_to_leagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueevent',
            name='away_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leagueevent',
            name='commence_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leagueevent',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leagueevent',
            name='home_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leagueevent',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
