# Generated by Django 4.2.19 on 2025-04-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_update_event_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='image',
            field=models.ImageField(blank=True, default='league_images/default_league.png', upload_to='league_images/'),
        ),
    ]
