# Generated by Django 4.2.19 on 2025-04-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_league_updated_at_alter_league_captain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='sports',
            field=models.JSONField(default=list),
        ),
    ]
