# Generated by Django 4.2.19 on 2025-04-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_alter_league_sports'),
    ]

    operations = [
    ]
