# Generated by Django 4.2.19 on 2025-04-03 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0007_auto_20250403_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='league',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='league',
            name='image',
            field=models.ImageField(blank=True, default='league_images/default_league.png', upload_to='league_images/'),
        ),
        migrations.AlterField(
            model_name='league',
            name='members',
            field=models.ManyToManyField(related_name='leagues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='league',
            name='sports',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='LeagueMembership',
        ),
    ]
