# Generated by Django 4.2.19 on 2025-04-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_update_default_image'),
        ('groups', '0011_alter_league_image'),
    ]

    operations = [
    ]
