# Generated by Django 4.2.19 on 2025-04-05 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_alter_league_image'),
    ]

    operations = [
    ]
