# Generated by Django 4.2.19 on 2025-04-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_chatmessage'),
        ('groups', '0013_circuit_leagueevent_betting_type_and_more'),
    ]

    operations = [
    ]
