# Generated by Django 4.2.19 on 2025-04-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_alter_circuit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitparticipant',
            name='completed_bets',
            field=models.ManyToManyField(blank=True, help_text='League events that this participant has already placed bets on.', related_name='circuit_participants_completed', to='groups.leagueevent'),
        ),
    ]
