# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/rosterroyals.com
cert = /etc/letsencrypt/live/rosterroyals.com/cert.pem
privkey = /etc/letsencrypt/live/rosterroyals.com/privkey.pem
chain = /etc/letsencrypt/live/rosterroyals.com/chain.pem
fullchain = /etc/letsencrypt/live/rosterroyals.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 4bc61b559729b78217eb72384baac6ba
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
