name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main # Or whichever branch triggers deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master 
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 # Default SSH port
          script: |
            set -e # Exit immediately if a command exits with a non-zero status.
            cd /root/roster-royals
            echo "Pulling latest code from main branch..."
            git pull origin main
            echo "Running database migrations..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml exec django-web python manage.py migrate
            echo "Rebuilding and restarting Docker containers..."
            docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build --no-cache react-app
            # Optional: Prune unused Docker images, containers, and volumes to save space
            # echo "Pruning Docker system..."
            # docker system prune -af
            echo "Deployment successful!" 